services:
  - type: web
    name: schulaufgabe-prometheus
    runtime: docker
    repo: https://github.com/isheglov/schulaufgabe.git
    rootDir: prometheus
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 9090
      - key: PROMETHEUS_METRICS_USERNAME
        sync: METRICS_USERNAME
      - key: PROMETHEUS_METRICS_PASSWORD
        sync: METRICS_PASSWORD
    autoDeploy: true
    region: frankfurt
    plan: free
    healthCheckPath: /-/healthy
