global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'schulaufgabe-backend'
    scheme: https
    static_configs:
      - targets: ['schulaufgabe-backend-docker.onrender.com']
    metrics_path: /metrics
    # Basic auth configuration - set these in environment variables
    basic_auth:
      username: "${PROMETHEUS_METRICS_USERNAME}"
      password: "${PROMETHEUS_METRICS_PASSWORD}"

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
