name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend (Next.js/TypeScript)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run TypeScript type check
        run: npx tsc --noEmit
      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx
      - name: Build Next.js app
        run: npm run build

  backend:
    name: Backend (Python/FastAPI)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn aiofiles python-multipart
      - name: Run black (code style)
        run: |
          pip install black
          black --check backend/
      - name: Run flake8 (linter)
        run: |
          pip install flake8
          flake8 backend/ 