name: Keep Render Services Alive

on:
  schedule:
    - cron: "*/13 6-23 * * *"  # Every 13 minutes between 6am and 11pm

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping frontend
        run: |
          JITTER=$((RANDOM % 120 + 1))
          echo "Sleeping for $JITTER seconds before ping..."
          sleep $JITTER
          curl -fsS https://schulaufgabe-frontend.onrender.com > /dev/null || echo "Ping failed"
      - name: Ping backend
        run: |
          JITTER=$((RANDOM % 120 + 1))
          echo "Sleeping for $JITTER seconds before ping..."
          sleep $JITTER
          curl -fsS https://schulaufgabe-backend-docker.onrender.com > /dev/null || echo "Ping failed"
